# This is a basic workflow to help you get started with Actions

name: libffi-build-macos-arm64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@vendors
      
      # Runs a single command using the runners shell
      - name: Run brew to install <automake, libtool, pkg-config>
        run: |
          brew update
          brew install automake libtool pkg-config
      
      # Runs a single command using the runners shell
      - name: Preconfigure for libffi
        working-directory: src/libffi-3.5.2
        run: chmod +x configure
      
      - name: Build libffi (arm64, macOS 11+)
        working-directory: src/libffi-3.5.2
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CC: "clang -arch arm64"
          CFLAGS: "-arch arm64 -mmacosx-version-min=11.0"
          LDFLAGS: "-arch arm64 -mmacosx-version-min=11.0"
        run: |
          sh ./configure \
            --host=arm-apple-darwin \
            --enable-static \
            --disable-shared \
            --prefix=$PWD/arm64

          make -j$(sysctl -n hw.ncpu)
          make install
          make clean
      
      - name: Verify architecture
        run: |
          file src/libffi-3.5.2/arm64/lib/libffi.a
          otool -l src/libffi-3.5.2/arm64/lib/libffi.a | grep -A2 LC_BUILD_VERSION
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libffi-arm64-macos11
          path: src/libffi-3.5.2/out-arm64
